services:
  - type: web
    name: docbook-backend
    env: node
    region: oregon
    branch: main
    plan: free
    buildCommand: 'cd backend && npm ci'
    startCommand: 'cd backend && npm start'
    autoDeploy: true
    pullRequestPreviewsEnabled: false
    envVars:
      - key: NODE_ENV
        value: production
  - type: static
    name: docbook-frontend
    region: oregon
    branch: main
    plan: free
    buildCommand: 'cd frontend && npm ci && npm run build'
    publishCommand: 'cd frontend && npm run build && cp -r dist ../_static_frontend || true'
    staticPublishPath: frontend/dist
    autoDeploy: true
    pullRequestPreviewsEnabled: false
    envVars:
      - key: VITE_API_URL
        value: 'https://docbook-lwjv.onrender.com'
